name: 'Veracode DAST Action'
description: 'Kick Off Veracode DAST Scan'
author: 'Vincent Deng'
inputs:
  vid:
    description: 'Veracode ID'
    required: true
  vkey:
    description: 'Veracode Key'
    required: true
  dast_config_file_name:
    description: 'Dast Config File Name'
    required: true
  token:
    description: 'your GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
  owner:
    description: 'owner of the repo'
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: 'repo name'
    required: true
    default: ${{ github.event.repository.name }}
runs:
  using: 'node20'
  main: 'dist/index.js'